# Generated by Django 4.2 on 2023-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='words_per_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
