# Generated by Django 4.2 on 2023-08-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_words_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
