# Generated by Django 4.2 on 2023-08-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
