# Generated by Django 4.2 on 2023-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='font_color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
