# Generated by Django 4.2 on 2023-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_word_remembered'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='edit_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='first_save_done',
            field=models.BooleanField(default=False),
        ),
    ]
