# Generated by Django 4.2 on 2023-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_page_edit_mode_page_first_save_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
