# Generated by Django 4.2 on 2023-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_word_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='repeated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
