# Generated by Django 4.2 on 2023-08-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_word_repeated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='remembered',
            field=models.BooleanField(),
        ),
    ]
