# Generated by Django 4.2 on 2023-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_word_remembered'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='start_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
