# Generated by Django 4.2 on 2023-08-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_page_start_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='start_number',
        ),
    ]
